[project]
title = "Happiness Explorer"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Happiness Explorer"
logo = "images/logo.png"
favicon = "😀"
primaryColor = "#F89613"

[data.world_happiness_report]
type = "csv"
path = "data/world_happiness_report.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 